name: renderer
description: A Falcon micro-framework package to manage UI states reactively based on custom BLoC and reactive extenstions
version: 0.0.7
repository: https://github.com/AKWAD-Dragons/Renderer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  rxdart: ^0.27.2
  get_it: ^7.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

